config/routes.rb
Rails.application.routes.draw do
  resources :images
  root to: "welcome#index"
  resources :welcome, only: [:index]
  resources :prompts, only: [:index, :show] do
    resources :crowd_stories
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crowd_story.rb
class CrowdStory < ApplicationRecord
  belongs_to :prompt
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :imagedata, PostImageUploader
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  has_many :crowd_stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crowd_stories_controller.rb
class CrowdStoriesController < ApplicationController
  # before_action :set_crowd_story, only: [:show, :update, :des

  # GET /crowd_stories


  # GET /crowd_stories/1
  def show
    render json: @crowd_story
  end

  # POST /crowd_stories
  def create
  @prompt = Prompt.find(params[:prompt_id])
  @crowd_story = @prompt.crowd_stories.create(crowd_story_params)
  redirect_to prompt_path(@prompt)
  end

  def edit
    @crowd_story = CrowdStory.find(params[:id])
  end

  # PATCH/PUT /crowd_stories/1
  def update
    @crowd_story = CrowdStory.update(params[:id])
    redirect_to prompts_path(@prompt)
  end

  # DELETE /crowd_stories/1
  def destroy
    @crowd_story = CrowdStory.find(params[:id])
    @crowd_story.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_crowd_story
    #   @crowd_story = CrowdStory.find(params[:id])
    # end

    # Only allow a trusted parameter "white list" through.
    def crowd_story_params
      params.require(:crowd_story).permit(:story, :title)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # before_action :set_image, only: [:show, :edit, :update, :destroy]
  # before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]


  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])
  end

  # GET /images/new
  def new
    @image = Image.new
  end



  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to images_url, notice: 'Image was successfully created.' }
        format.json { render :index, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :imagedata)
    end
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  before_action :set_prompt, only: [:show]

  # GET /prompts
  def index
    @prompts = Prompt.all

    # render json: @prompts
  end

  # GET /prompts/1
  def show
    @prompt
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prompt
      @prompt = Prompt.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def prompt_params
      params.require(:prompt).permit(:writing_prompt)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def index
    
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= simple_form_for(@image) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :imagedata %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<div class="title">
  <h1>Images</h1>
</div>

<div class="image-container">
 <% @images.each do |image| %>
   <%= link_to image_path(image) do %>
   <%= image_tag image.imagedata.thumb.url, class: "image-links" %>
   <% end %>
 <% end %>

</div>

<br>
<div class="foot">
  <%= link_to 'New Image', new_image_path, class: "text-link" %>
  <br>
  <%= link_to "Home", welcome_index_url, class: "text-link" %>
</div>

app/views/images/new.html.erb
<div class="title">
  <h1>New Image</h1>

</div>
<div class="story-form">
  <%= render 'form', image: @image %>
</div>

<div class="foot">
  <%= link_to 'Back', images_path, class: "back-link" %>

</div>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<div class="image-title">
  <h2 class="art-title"><%= @image.title %></h2>
</div>

<div class="container">
  <%= image_tag @image.imagedata.large.url, class: "image-large" %>

</div>
<div class="foot">
  <%= link_to 'Back', images_path, class: "back-link" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SciWrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prompts/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    Edit Page
  </body>
</html>

app/views/prompts/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="title">
      <h1>Writing Prompts</h1>
    </div>

    <div class="container-prompt">
      <div class="prompt">
        <% @prompts.each do |prompt| %>
        <h2 class="writing-prompt"><%= link_to prompt.writing_prompt, prompt_path(prompt), class: "text-link" %></h2>
        <% end %>
      </div>
    </div>
    <br>
    <div class="foot">
      <%= link_to "Home", welcome_index_url, class: "back-link" %>
    </div>

  </body>
</html>

app/views/prompts/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h2 class="writing-prompt"><%= @prompt.writing_prompt %></h2>

    <% @prompt.crowd_stories.each do |crowd_story| %>
    <div class="comments">


    <strong><h3>
      <%=crowd_story.title %>
    </h3></strong>
      <p>
      <%=crowd_story.story %>
    </p>
    </div>
    <% end %>

  <div class="story-form">
    <h3>Add to the Story!</h3>
  <%= simple_form_for [@prompt, @prompt.crowd_stories.build] do |f| %>
  <%=f.input :title %>
  <%=f.input :story %>
  <%=f.submit "Add to Story" %>
  <%end%>
      </div>
      <br>

      <div class="foot">
        <%= link_to "Back to Prompts", prompts_path, class: "back-link"  %>
      </div>

  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="title">
      <h1>SciWrite</h1>
    </div>
    <div class="container">
      <div class="nav">
        <%= link_to "Writing Prompts", prompts_path, class: "text-link" %>
      </div>
      <div class="nav">
        <%= link_to "Image Gallery", images_path, class: "text-link" %>
      </div>

    </div>

  </body>
</html>